### ISSUE TITLE
Can't create decks from mtggoldfish.com

### ISSUE THREAD

**Issue by MaxVonBurritos** [jeandeaual/tts-deckconverter#10]
The error is 'Couldn't parse deck(s): no title found in https://www.mtggoldfish.com/deck/3433236#paper (XPath: //h1[contains(@class,'deck-view-title')]/text())

**Comment by jeandeaual** [comment]
@MaxVonBurritos Thanks for the report, and sorry for the inconvenience. It looks like mtggoldfish.com changed their layout, so the title of the deck can no longer be parsed.

I really need to setup some kind of periodic testing of all supported URLs…

I made a fix in ad9bc37d8327761f28103db71ce47faa3c93c23d, which will be available in the next release.
You can test it right now [here](https://github.com/jeandeaual/tts-deckconverter/suites/1261142125/artifacts/19315596) if you're using Windows or [here](https://github.com/jeandeaual/tts-deckconverter/suites/1261142125/artifacts/19315595) if you're using macOS.

**Comment by MaxVonBurritos** [comment]
Wow, thanks for the fast response and fix, that worked perfectly!

**Comment by jeandeaual** [comment]
Great, I'll close this issue then.

I've added [some automated tests](https://github.com/jeandeaual/tts-deckconverter/actions?query=workflow%3Atest-urls) for most of the supported URLs that will run every week, so hopefully this kind of issue will be easier to detect in the future.
