### ISSUE TITLE
Doesn't pull the correct printing of basic lands when specified

### ISSUE THREAD

**Issue by benicetodan** [jeandeaual/tts-deckconverter#11]
For example, if I specifiy 1x Forest (IKO) it pulls the latest printing from (ZNR) instead of what I specified.  I've had this happen both when pulling from tappedout and when generating from text.

**Comment by benicetodan** [comment]
ok upon further inspection the bug appears to only happen if I specify multiple different editions of the same card. It'll take the edition of the first card that it finds in the list, and all of the rest will be counted as just another of the same card.  in parser.go, the InsertCount function is what does this. I was able to "fix" the issue by commenting out a few lines:

// InsertCount inserts several new cards in a CardNames struct.
func (c *CardNames) InsertCount(name string, set *string, count int) {
	//_, found := c.Counts[name]
	//if !found {
		c.Names = append(c.Names, CardInfo{
			Name: name,
			Set:  set,
		})
		c.Counts[name] = count
	//} else {
	//	c.Counts[name] = c.Counts[name] + count
	//}
}

**Comment by jeandeaual** [comment]
Thanks for the report and for finding the source of the issue!
I'm working on a fix.

**Comment by jeandeaual** [comment]
@benicetodan I published a fix in [v0.6.1](https://github.com/jeandeaual/tts-deckconverter/releases/tag/v0.6.1).
Please let me know if this works for you.

**Comment by jeandeaual** [comment]
@benicetodan A fix has been published, so I'm closing this issue. Feel free to re-open it if it wasn't solved for you.
