### ISSUE TITLE
[MTG] Include card types and converted mana cost in card nickname field

### ISSUE THREAD

**Issue by tommadness** [jeandeaual/tts-deckconverter#2]
When searching a deck for a card, Tabletop Simulator searches in the nickname field for any relevant text. Including the card types and CMC in the name field would make tutoring for cards with those specific qualities (Human, Aura, Enchantment, 4CMC, etc.) easier.

**Comment by jeandeaual** [comment]
@tommadness Thank you for providing some feedback! That's indeed a good idea.
I added the card type and CMC in the nickname field in 9d8637b.
It will be included in the next release, but in the meantime you can test it [here](https://github.com/jeandeaual/tts-deckconverter/suites/738453926/artifacts/7469244) (if you're on Windows).

**Comment by tommadness** [comment]
Just gave this a test with a couple of decks, everything seems to be working as intended!
