### ISSUE TITLE
Import from deckstats.net is not correctly pulling the correct card image for the Kaladash Inventions Sets

### ISSUE THREAD

**Issue by Aznlilly86** [jeandeaual/tts-deckconverter#5]
The set is just whatever set it happened to pick as far as I can see.

**Comment by LoardVader** [comment]
I've been unable to get the program, to pull set specific art from any website, always just the latest art.

**Comment by jeandeaual** [comment]
@Aznlilly86 Can you tell me which URL or deck file you're trying to import exactly? Is it [this one](https://deckstats.net/set-breakdown/Masterpiece+Series%3A+Kaladesh+Inventions)?

@LoardVader If the set is not specified by the deck, the art from the latest set the card was released in will be used. It depends if the website sets the set name or not for each cardwhen exporting a deck. Which website do you have an issue with?

**Comment by jeandeaual** [comment]
By the way, if you're using the _From text_ tab instead of _From URL_, you can use [this method](https://github.com/jeandeaual/tts-deckconverter/pull/3#issuecomment-650671406) to pull specific art for a card.

**Comment by Aznlilly86** [comment]
I was using the deckstats.net site, here is an example deck: https://deckstats.net/decks/161156/1740667-fblthp-proteus-scepter-combo

**Comment by LoardVader** [comment]
i've been using "From URL" on scryfall

**Comment by jeandeaual** [comment]
@Aznlilly86 @LoardVader Thanks, I see the issue now. It seems that deckstats.net uses [some set names](https://deckstats.net/sets/?lng=en) (the ones with an underscore, like `MPS_KLD` for Kaladesh Inventions) that are different from the names used by [Scryfall](https://scryfall.com/sets) (which expects `MPS` for Kaladesh Inventions).

I made a manual fix for these set names in 0f675771f351815537b6906e662a6a4e6637b517, which seems to be working:

![20200906222809_1](https://user-images.githubusercontent.com/23304955/92327342-ddc8bb00-f093-11ea-85a7-276f62520331.jpg)

It will be included in the next release, but in the meantime you can test it [here](https://github.com/jeandeaual/tts-deckconverter/suites/1151090358/artifacts/16592224) (if you're on Windows).

**Comment by Aznlilly86** [comment]
The newly updated version works flawlessly for me so far.

**Comment by jeandeaual** [comment]
I released this fix as part of [v0.6](https://github.com/jeandeaual/tts-deckconverter/releases/tag/v0.6), so I'm closing the issue.
Please feel free to re-open it if it doesn't work for you.
