### ISSUE TITLE
Tool crashes with this deck from deckstats.net

### ISSUE THREAD

**Issue by Aznlilly86** [jeandeaual/tts-deckconverter#6]
When I run the tool, it silently crashes with no errors and nothing in the log while trying to import this deck:

https://deckstats.net/decks/161156/1763076-kaalia-stax

**Comment by jeandeaual** [comment]
According to the console log, this deck fails on the `Valakut Awakening` card.
It seems that we don't handle modal double-faced cards properly.

**Comment by jeandeaual** [comment]
Currently waiting for https://github.com/BlueMonday/go-scryfall/pull/24 to be merged.

**Comment by jeandeaual** [comment]
@Aznlilly86 I made a fix in 7f9b671dcbde42a08462466b57969f7d59656efa, which is available as part of [v0.6](https://github.com/jeandeaual/tts-deckconverter/releases/tag/v0.6).
With this, https://deckstats.net/decks/161156/1763076-kaalia-stax is now properly generated for me.
Please let me know if it fixed your issue.

**Comment by jeandeaual** [comment]
@Aznlilly86 A fix has been published, so I'm closing this issue. Feel free to re-open it if it wasn't solved for you.
