### ISSUE TITLE
Failed to parse on moxfield

### ISSUE THREAD

**Issue by untraceablez** [jeandeaual/tts-deckconverter#7]
**Describe the bug**
When pasting in a deck URL from moxfield.com, the deck fails to import, a card will fail its fuzzy match and the request will timeout. The card that fails changes each time. 

**To Reproduce**
1. Select a Moxfield deck, and copy the URL.
2. Paste URL into ttsdeckconverter-gui
3. Wait for the error code.

**Expected behavior**
Deck should finish generating and there should be notice it's been added to the specified directory. 

**Desktop (please complete the following information):**
 - Program: ttsdeckconverter-gui for Windows
 - OS: [e.g. Windows]
 - Version: May 24th release.

**Additional context**
This problem seems to have started in the last few days. Archidekt decks do seem to work, have not tested other deckbuilding sites.

**Comment by jeandeaual** [comment]
@untraceablez Thanks for the report!
It seems that the API I used to download deck from moxfield.com is not available anymore.
I switched to v2 of their API in 1d67ffed79c5502b4e77a5fc2e291d3c7c2f93a0, which is available as part of [v0.6](https://github.com/jeandeaual/tts-deckconverter/releases/tag/v0.6).
With this release, moxfield.com link are now working again for me. Please let me know if this fixed your issue.

**Comment by untraceablez** [comment]
@jeandeaual Sweet! I'll take a look at it today after I get done with work, thank you for the work on a quick fix!

**Comment by jeandeaual** [comment]
@untraceablez A fix has been published, so I'm closing this issue. Feel free to re-open it if it wasn't solved for you.
