### ISSUE TITLE
Fails to parse counterbalance

### ISSUE THREAD

**Issue by Aznlilly86** [jeandeaual/tts-deckconverter#8]
The tool says it can't load this deck because of counterbalance:
https://deckstats.net/decks/161156/1769395-memnarch

**Comment by Aznlilly86** [comment]
So it seems that it specifically does not parse the amonkhet masterpiece version

**Comment by jeandeaual** [comment]
@Aznlilly86 Thanks for the bug report!

It seems that the fix done in #5 was not enough to handle all the set names that differ between deckstats.net and Scryfall.

I made a fix in b23cb39607608553ef51e524a269eb4056d6f881, which will be included in the next release.
In the meantime you can test it [here](https://github.com/jeandeaual/tts-deckconverter/suites/1255416129/artifacts/19167999) if you're using Windows or [here](https://github.com/jeandeaual/tts-deckconverter/suites/1255416129/artifacts/19167998) if you're using macOS.

**Comment by jeandeaual** [comment]
@Aznlilly86 A fix has been published, so I'm closing this issue. Feel free to re-open it if it wasn't solved for you.
